### ISSUE TITLE
Does not render Pipeline Build Link

### ISSUE THREAD

**Issue by AnthonyBarbier** [jenkinsci/pipeline-graph-view-plugin#59]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text

I don't have admin access to our Jenkins instance, let me know if you think this information is important for that particular bug and I'll ask one of our infrastructure engineers.
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu

### Reproduction steps

Similar to the Blue Ocean issue: https://issues.jenkins.io/browse/JENKINS-38339

When using `parallel` the links to the child jobs are removed and only the link name remains.
Regular Console:
![Console](https://user-images.githubusercontent.com/5241909/159545982-f83057bb-a62c-48cb-9637-ab0c4dd71221.png)

Plugin:
![plugin](https://user-images.githubusercontent.com/5241909/159545983-fc141a23-ce97-4b43-a5a3-5dfbc9842223.png)

### Expected Results

Either a link with the label + URL, or at least for the label to be replaced with the URL as this is more useful than just the text.

### Actual Results

Only the text / label for the URL is displayed.

**Comment by timbrown5** [comment]
The core of the issue is the way the Jenkins console API is structured. You either get the raw console text (which both plugins use) or a heavily annotated text (which includes all annotations for installed plugins). The issue with that is all the plugins have only been designed to work with the Console view. Once you start changing the underlying structure weird things start happening (e.g thread markers being on wrong lines or overlapping other UI elements).

In short:
[https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/5a693b766483239621551[…]ns/pipelinegraphview/consoleview/PipelineConsoleViewAction.java](https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/5a693b7664832396215511ce79a2975138bafb71/src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java#L87)
uses:
https://javadoc.jenkins.io/hudson/console/AnnotatedLargeText.html#writeLogTo-long-java.io.OutputStream-
instead of:
https://javadoc.jenkins.io/hudson/console/AnnotatedLargeText.html#writeRawLogTo-long-java.io.OutputStream-
(the names are a little confusing, raw is the Jenkins annotate log, not the raw console output).
